export { default as calculatorInsurer } from "./calculator-insurer.vue"
export { default as calculatorPassport } from "./calculator-passport.vue"
export { default as calculatorForeigner } from "./calculator-foreigner.vue"
export { default as calculatorAddress } from "./calculator-address.vue"
export { default as calculatorCompanyAddress } from "./calculator-company-address.vue"
export { default as calculatorSignatory } from "./calculator-signatory.vue"
