export { default as calculatorRegistrationAdditional } from "./calculator-registration-additional.vue"
export { default as calculatorBeneficiary } from "./calculator-beneficiary.vue"
export { default as calculatorPlacement } from "./calculator-placement.vue"
export { default as calculatorContract } from "./calculator-contract.vue"
export { default as calculatorParent } from "./calculator-parent.vue"
export { default as calculatorBank } from "./calculator-bank.vue"
